# Generated by Django 5.2.16 on 2026-07-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_ats_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='resumebuilder',
            name='resume_file',
        ),
    ]
